import { Folder } from "@/types";

export const FooterMessages = [
  {
    name: "Folder",
    message: "Creates a new folder.",
  },
  {
    name: "Shortcut",
    message: "Creates a shortcut to quickly access your files or applications.",
  },
  {
    name: "TextDocument",
    message: "Creates a new text document for your notes and simple writings.",
  },
  {
    name: "WordPadDocument",
    message: "Creates a new WordPad document for rich text editing.",
  },
  {
    name: "BitmapImage",
    message: "Creates a new bitmap image for your drawings and graphics.",
  },
  {
    name: "WaveSound",
    message: "Creates a new wave sound file for your audio recordings.",
  },
  {
    name: "CreateShortcut",
    message: "Creates shortcuts to the selected items.",
  },
  {
    name: "Delete",
    message: "Deletes the selected item.",
  },
  {
    name: "Rename",
    message: "Renames the selected item.",
  },
  {
    name: "Properties",
    message: "Displays the properties of the selected items.",
  },
  {
    name: "WorkOffline",
    message: "Shows Web pages without downloading them.",
  },
  {
    name: "Close",
    message: "Closes the current window.",
  },
  {
    name: "Undo",
    message: "Undo the last action.",
  },
  {
    name: "CutCtrl+X",
    message: "Removes the selected items and copies them onto the Clipboard.",
  },
  {
    name: "CopyCtrl+C",
    message:
      "Copies the selected items to the Clipboard. To put them in the new location, use the Paste command.",
  },
  {
    name: "PasteCtrl+V",
    message:
      "Inserts the items you have copied or cut into the selected location.",
  },
  {
    name: "PasteShortcut",
    message:
      "Creates shortcuts to the items you have copied or cut into the selected location.",
  },
  {
    name: "SelectAllCtrl+A",
    message: "Select all items in window.",
  },
  {
    name: "InvertSelection",
    message: "Reverses which items are selected and which are not.",
  },
  {
    name: "StandardButtons",
    message: "Displays the Standard Buttons toolbar.",
  },
  {
    name: "AddressBar",
    message: "Displays the Address bar.",
  },
  {
    name: "Links",
    message: "Displays the Quick Links bar.",
  },
  {
    name: "Radio",
    message: "Displays the Radio bar.",
  },
  {
    name: "TextLabels",
    message: "Adds a text label under each toolbar button.",
  },
  {
    name: "StatusBar",
    message: "Shows or hides the status bar.",
  },
  {
    name: "SearchCtrl+E",
    message: "Shows the Search bar.",
  },
  {
    name: "FavoritesCtrl+I",
    message: "Shows the Favorites bar.",
  },
  {
    name: "HistoryCtrl+H",
    message: "Shows the History bar.",
  },
  {
    name: "Folders",
    message: "Shows the Folders bar.",
  },
  {
    name: "TipoftheDay",
    message: "Shows a tip about the system.",
  },
  {
    name: "asWebPage",
    message: "Displays items in Web View.",
  },
  {
    name: "LargeIcons",
    message: "Displays items by using large icons.",
  },
  {
    name: "SmallIcons",
    message: "Displays items by using small icons.",
  },
  {
    name: "List",
    message: "Displays items in a list.",
  },
  {
    name: "Details",
    message: "Displays information about each item in the window.",
  },
  {
    name: "byName",
    message: "Sorts items alphabetically by name.",
  },
  {
    name: "byType",
    message: "Sorts items by type.",
  },
  {
    name: "bySize",
    message: "Sorts items by size, from smallest to largest.",
  },
  {
    name: "byDate",
    message: "Sorts items by date, from oldest to most recent.",
  },
  {
    name: "AutoArrange",
    message: "Arranges the icons automatically.",
  },
  {
    name: "LineUpIcons",
    message: "Arranges icons in a grid.",
  },
  {
    name: "RefreshF5",
    message: "Refreshes the content of current page.",
  },
  {
    name: "FolderOptions...",
    message: "Enables you to change settings.",
  },
  {
    name: "BackAlt+LeftArrow",
    message: "Goes to the previous page.",
  },
  {
    name: "ForwardAlt+RightArrow",
    message: "Goes to the next page.",
  },
  {
    name: "UpOneLevel",
    message: "Goes up one level.",
  },
  {
    name: "HomePageAlt+Home",
    message: "Goes to your home page.",
  },
  {
    name: "ChannelGuide",
    message: "Opens the Channel Guide page.",
  },
  {
    name: "SearchtheWeb",
    message: "Opens Internet Explorer.",
  },
  {
    name: "MyComputer",
    message: "Opens My Computer.",
  },
  {
    name: "InternetCall",
    message: "Opens your Internet call and meeting program.",
  },
  {
    name: "AddtoFavorites...",
    message: "Adds the current page to your Favorites list.",
  },
  {
    name: "OrganizeFavorites...",
    message: "Opens the Favorites folder.",
  },
  {
    name: "(empty)",
    message: "I'm just an empty space.",
  },
  {
    name: "FilesorFolders...",
    message: "Searches for Files or Folders.",
  },
  {
    name: "Computer...",
    message: "Searches on Computer settings.",
  },
  {
    name: "OntheInternet...",
    message: "Searches on the Internet.",
  },
  {
    name: "MapNetworkDrive...",
    message: "Connects to a network drive.",
  },
  {
    name: "DisconnectNetworkDrive...",
    message: "Disconnects from a network drive.",
  },
  {
    name: "Synchronize...",
    message: "Updates all offline content.",
  },
  {
    name: "HelpTopics",
    message: "Opens Help.",
  },
  {
    name: "About98.portfolio",
    message: "Opens the 98.portfolio document.",
  },
];

export const folders: Folder[] = [
  {
    id: 1,
    name: "Recycle Bin",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/recycle-bin.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 2,
    name: "My Computer",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/computer-explorer.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 3,
    name: "Backend",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/folder.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 4,
    name: "Frontend",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/folder.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 5,
    name: "Mobile",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/folder.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 7,
    name: "98.portfolio",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/help-book.png",
    isDocument: true,
    documentType: "markdown",
    documentPath: "/AlexandreDresch/98.portfolio",
  },
  {
    id: 8,
    name: "Contact me",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/modem.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 17,
    name: "Games",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/folder.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 18,
    name: "Control Panel",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/control-panel.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
];

export const programs = [
  {
    id: 9,
    name: "VS Code",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/vscode.png",
  },
  {
    id: 10,
    name: "Internet Explorer",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/internet-explorer.png",
  },
  {
    id: 11,
    name: "Image Viewer",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/kodak-image.png",
  },
  {
    id: 12,
    name: "Notepad",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/notepad.png",
  },
  {
    id: 13,
    name: "Calculator",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/calculator.png",
  },
  {
    id: 14,
    name: "Paint",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/paint.png",
  },
  {
    id: 15,
    name: "98.DOOM",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    description: "Fight the BSOD demons in this Doom inspired game.",
    image: "/icons/98.doom.png",
  },
  {
    id: 16,
    name: "MS-DOS Prompt",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/console-prompt.png",
  },
  {
    id: 19,
    name: "Display",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/display.png",
    description: "Adjust display settings such as resolution and color depth.",
  },
  {
    id: 20,
    name: "Keyboard",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/keyboard.png",
    description: "Configure keyboard settings and preferences.",
  },
  {
    id: 21,
    name: "Mouse",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/mouse.png",
    description:
      "Modify mouse settings including pointer speed and button configuration.",
  },
  {
    id: 22,
    name: "Date/Time",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/date-time.png",
    description: "Set the system date and time, as well as time zone settings.",
  },
  {
    id: 23,
    name: "System",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/system.png",
    description: "View and manage system information and hardware settings.",
  },
  {
    id: 24,
    name: "Winamp",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/winamp.png",
    description:
      "A classic media player for playing your favorite music (using Youtube).",
  },
  {
    id: 25,
    name: "Document Viewer",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/file.png",
    description: "View and read documents in various formats.",
  }
];

export const folderNavigationMenuItems = {
  file: [
    {
      label: "New",
      items: [
        { label: "Folder", disabled: true },
        { label: "Shortcut", disabled: true },
        { label: "Text Document", disabled: true },
        { label: "WordPad Document", disabled: true },
        { label: "Bitmap Image", disabled: true },
        { label: "Wave Sound", disabled: true },
      ],
    },
    { label: "Create Shortcut", disabled: true },
    { label: "Delete" },
    { label: "Rename" },
    { label: "Properties", disabled: true },
    { label: "Work Offline" },
    { label: "Close" },
  ],
  edit: [
    { label: "Undo", disabled: true },
    { label: "Cut", disabled: true, shortcut: "Ctrl+X" },
    { label: "Copy", disabled: true, shortcut: "Ctrl+C" },
    { label: "Paste", disabled: true, shortcut: "Ctrl+V" },
    { label: "Paste Shortcut", disabled: true },
    { label: "Select All", shortcut: "Ctrl+A" },
    { label: "Invert Selection" },
  ],
  view: [
    {
      label: "Toolbars",
      items: [
        { label: "Standard Buttons" },
        { label: "Address Bar" },
        { label: "Links", disabled: true },
        { label: "Radio", disabled: true },
        { label: "Text Labels" },
      ],
    },
    { label: "Status Bar" },
    {
      label: "Explorer Bar",
      items: [
        { label: "Search", disabled: true, shortcut: "Ctrl+E" },
        { label: "Favorites", disabled: true, shortcut: "Ctrl+I" },
        { label: "History", disabled: true, shortcut: "Ctrl+H" },
        { label: "Folders", disabled: true },
        { label: "Tip of the Day", disabled: true },
      ],
    },
    { label: "as Web Page" },
    { label: "Large Icons" },
    { label: "Small Icons" },
    { label: "List" },
    { label: "Details", disabled: true },
    {
      label: "Arrange Icons",
      items: [
        { label: "by Name" },
        { label: "by Type" },
        { label: "by Size" },
        { label: "by Date" },
        { label: "Auto Arrange", disabled: true },
      ],
    },
    { label: "Line Up Icons", disabled: true },
    { label: "Refresh", shortcut: "F5" },
    { label: "Folder Options...", disabled: true },
  ],
  go: [
    { label: "Back", disabled: true, shortcut: "Alt+Left Arrow" },
    { label: "Forward", disabled: true, shortcut: "Alt+Right Arrow" },
    { label: "Up One Level" },
    { label: "Home Page", shortcut: "Alt+Home" },
    { label: "Channel Guide" },
    { label: "Search the Web" },
    { label: "My Computer" },
    { label: "Internet Call" },
  ],
  favorites: [
    { label: "Add to Favorites...", disabled: true },
    { label: "Organize Favorites...", disabled: true },
    { label: "(empty)", disabled: true },
  ],
  tools: [
    {
      label: "Find",
      items: [
        { label: "Files or Folders...", disabled: true },
        { label: "Computer...", disabled: true },
        { label: "On the Internet...", disabled: true },
      ],
    },
    { label: "Map Network Drive..." },
    { label: "Disconnect Network Drive..." },
    { label: "Synchronize..." },
  ],
  help: [
    { label: "Help Topics", disabled: true },
    { label: "About 98.portfolio" },
  ],
};

export const vscodeNavigationMenuItems = {
  file: [
    { label: "New Text File", shortcut: "Ctrl+N" },
    { label: "New File...", shortcut: "Alt+Ctrl+N" },
    { label: "New Window", shortcut: "Ctrl+Shift+N" },
    {
      label: "New Window with Profile",
      items: [{ label: "New Profile..." }],
    },
    { label: "Open File...", shortcut: "Ctrl+O" },
    { label: "Open Folder... [Ctrl+K Ctrl+O]" },
    { label: "Open Workspace from File..." },
    {
      label: "Open Recent",
      items: [
        { label: "Reopen Closed Editor", shortcut: "Ctrl+Shift+T" },
        { label: "~/Documents/GitHub/98.portfolio" },
        { label: "More...", shortcut: "Ctrl+R" },
        { label: "Clear Recently Opened..." },
      ],
    },
    { label: "Add Folder to Workspace..." },
    { label: "Save Workspace as..." },
    { label: "Duplicate Workspace" },
    { label: "Save", shortcut: "Ctrl+S" },
    { label: "Save As...", shortcut: "Ctrl+Shift+S" },
    { label: "Save All" },
    {
      label: "Share",
      items: [
        { label: "Copy vscode.dev Link" },
        { label: "Copy GitHub Permalink" },
        { label: "Copy GitHub Permalink as Markdown" },
        { label: "Copy GitHub Head Link" },
        { label: "Export Profile (Default)..." },
        { label: "Import Profile..." },
      ],
    },
    { label: "Auto Save" },
    {
      label: "Preferences",
      items: [
        { label: "Profile (Default)" },
        { label: "Settings [Ctrl+,]" },
        { label: "Extensions", shortcut: "Ctrl+Shift+X" },
        { label: "Keyboard Shortcuts [Ctrl+K Ctrl+S]" },
        { label: "Configure Snippets" },
        { label: "Tasks" },
        {
          label: "Theme",
          items: [
            { label: "Color Theme [Ctrl+K Ctrl+Q]" },
            { label: "File Icon Theme" },
            { label: "Product Icon Theme" },
          ],
        },
        { label: "Settings Sync is On" },
        { label: "Online Services Settings" },
      ],
    },
    { label: "Revert File" },
    { label: "Close Editor", shortcut: "Ctrl+W" },
    { label: "Close Folder [Ctrl+K F]" },
    { label: "Close Window", shortcut: "Alt+F4" },
    { label: "Exit", shortcut: "Ctrl+Q" },
  ],
  edit: [
    { label: "Undo", shortcut: "Ctrl+Z" },
    { label: "Redo", shortcut: "Ctrl+Y" },
    { label: "Cut", shortcut: "Ctrl+X" },
    { label: "Copy", shortcut: "Ctrl+C" },
    {
      label: "Copy As",
      items: [
        { label: "Copy GitHub Permalink" },
        { label: "Copy GitHub Permalink as Markdown" },
      ],
    },
    { label: "Paste", shortcut: "Ctrl+V" },
    { label: "Find", shortcut: "Ctrl+F" },
    { label: "Replace", shortcut: "Ctrl+H" },
    { label: "Find in Files", shortcut: "Ctrl+Shift+F" },
    { label: "Replace in Files", shortcut: "Ctrl+Shift+H" },
    { label: "Toggle Line Comment [Ctrl+]" },
    { label: "Toggle Block Comment", shortcut: "Ctrl+Shift+A" },
    { label: "Emmet: Expand Abbreviation", shortcut: "Tab" },
  ],
  selection: [
    { label: "Select All", shortcut: "Ctrl+A" },
    { label: "Expand Selection", shortcut: "Alt+Shift+Right Arrow" },
    { label: "Shrink Selection", shortcut: "Alt+Shift+Left Arrow" },
    { label: "Copy Line Up", shortcut: "Alt+Ctrl+Shift+Up Arrow" },
    { label: "Copy Line Down", shortcut: "Alt+Ctrl+Shift+Down Arrow" },
    { label: "Move Line Up", shortcut: "Alt+Up Arrow" },
    { label: "Move Line Down", shortcut: "Alt+Down Arrow" },
    { label: "Duplicate Selection" },
    { label: "Add Cursor Above", shortcut: "Alt+Shift+Up Arrow" },
    { label: "Add Cursor Bellow", shortcut: "Alt+Shift+Down Arrow" },
    { label: "Add Cursors to Line Ends", shortcut: "Alt+Shift+I" },
    { label: "Add Next Occurrence", shortcut: "Ctrl+D" },
    { label: "Add Previous Occurrence" },
    { label: "Select All Occurrences", shortcut: "Ctrl+Shift+L" },
    { label: "Switch to Ctrl+Click for Multi-Cursor" },
    { label: "Column Selection Mode" },
  ],
  view: [
    { label: "Command Palette...", shortcut: "Ctrl+Shift+P" },
    { label: "Open View..." },
    {
      label: "Appearance",
      items: [
        { label: "Fullscreen", shortcut: "F11" },
        { label: "Zen Mode [Ctrl+K Z]" },
        { label: "Centered Layout" },
        { label: "Menu Bar" },
        { label: "Primary Side Bar", shortcut: "Ctrl+B" },
        { label: "Secondary Side Bar", shortcut: "Alt+Ctrl+B" },
        { label: "Status Bar" },
        { label: "Panel", shortcut: "Ctrl+J" },
        { label: "Custom Title Bar" },
        { label: "Move Primary Side Bar Right" },
        {
          label: "Active Bar Position",
          items: [
            { label: "Default" },
            { label: "Top" },
            { label: "Bottom" },
            { label: "Hidden" },
          ],
        },
        {
          label: "Panel Position",
          items: [
            { label: "Top" },
            { label: "Left" },
            { label: "Right" },
            { label: "Bottom" },
          ],
        },
        {
          label: "Align Panel",
          items: [
            { label: "Center" },
            { label: "Justify" },
            { label: "Left" },
            { label: "Right" },
          ],
        },
        {
          label: "Tab Bar",
          items: [
            { label: "Multiple Tabs" },
            { label: "Single Tab" },
            { label: "Hidden" },
          ],
        },
        {
          label: "Editor Actions Position",
          items: [
            { label: "Tab Bar" },
            { label: "Title Bar" },
            { label: "Hidden" },
          ],
        },
        { label: "Minimap" },
        { label: "Toggle Breadcrumbs" },
        { label: "Sticky Scroll" },
        { label: "Render Whitespace" },
        { label: "Render Control Characters" },
        { label: "Zoom In [Ctrl+=]" },
        { label: "Zoom Out [Ctrl+-]" },
        { label: "Reset Zoom [Ctrl+Numpad0]" },
      ],
    },
    {
      label: "Editor Layout",
      items: [
        { label: "Split Up [Ctrl+K Ctrl+]" },
        { label: "Split Down" },
        { label: "Split Left" },
        { label: "Split Right" },
        { label: "Split in Group [Ctrl+K Ctrl+Shift+]" },
        { label: "Move Editor into New Window" },
        { label: "Copy Editor into New Window [Ctrl+K O]" },
        { label: "Single" },
        { label: "Two Columns" },
        { label: "Three Columns" },
        { label: "Two Rows" },
        { label: "Three Rows" },
        { label: "Grid (2x2)" },
        { label: "Two Rows Right" },
        { label: "Two Columns Bottom" },
        { label: "Flip Layout", shortcut: "Alt+Shift+0" },
      ],
    },
    { label: "Explorer", shortcut: "Ctrl+Shift+E" },
    { label: "Search", shortcut: "Ctrl+Shift+F" },
    { label: "Source Control", shortcut: "Ctrl+Shift+G" },
    { label: "Run", shortcut: "Ctrl+Shift+D" },
    { label: "Extensions", shortcut: "Ctrl+Shift+X" },
    { label: "Problems", shortcut: "Ctrl+Shift+M" },
    { label: "Output [Ctrl+K Ctrl+H]" },
    { label: "Debug Console", shortcut: "Ctrl+Shift+Y" },
    { label: "Output [Ctrl+Shift+´]" },
    { label: "Word Wrap", shortcut: "Alt+Z" },
  ],
  go: [
    { label: "Back" },
    { label: "Forward [Ctrl+Shift+-]", disabled: true },
    { label: "Last Edit Location [Ctrl+K Ctrl+Q]" },
    {
      label: "Switch Editor",
      items: [
        { label: "Next Editor", shortcut: "Ctrl+Page Down" },
        { label: "Previous Editor", shortcut: "Ctrl+Page Up" },
        { label: "Next Used Editor" },
        { label: "Previous Used Editor" },
        { label: "Next Editor in Group [Ctrl+K Ctrl+PageDown]" },
        { label: "Previous Editor in Group [Ctrl+K Ctrl+PageUp]" },
        { label: "Next Used Editor in Group" },
        { label: "Previous Used Editor in Group" },
      ],
    },
    {
      label: "Switch Group",
      items: [
        { label: "Group 1", shortcut: "Ctrl+1" },
        { label: "Group 2", shortcut: "Ctrl+2" },
        { label: "Group 3", shortcut: "Ctrl+3", disabled: true },
        { label: "Group 4", shortcut: "Ctrl+4", disabled: true },
        { label: "Group 5", shortcut: "Ctrl+5", disabled: true },
        { label: "Next Group", disabled: true },
        { label: "Previous Group", disabled: true },
        { label: "Group Left [Ctrl+K Ctrl+LeftArrow]", disabled: true },
        { label: "Group Right [Ctrl+K Ctrl+RightArrow]", disabled: true },
        { label: "Group Above [Ctrl+K Ctrl+UpArrow]", disabled: true },
        { label: "Group Bellow [Ctrl+K Ctrl+DownArrow]", disabled: true },
      ],
    },
    { label: "Go to File...", shortcut: "Ctrl+P" },
    { label: "Go to Symbol in Workspace...", shortcut: "Ctrl+T" },
    { label: "Go to Definition", shortcut: "F12" },
    { label: "Go to Declaration" },
    { label: "Go to Type Definition" },
    { label: "Go to Implementations", shortcut: "Ctrl+F12" },
    { label: "Go to References", shortcut: "Shift+F12" },
    { label: "Go to Line/Column...", shortcut: "Ctrl+G" },
    { label: "Go to Bracket [Ctrl+Shift+]" },
    { label: "Next Problem", shortcut: "F8" },
    { label: "Previous Problem", shortcut: "Shift+F8" },
    { label: "Next Change", shortcut: "Alt+F3" },
    { label: "Previous Change", shortcut: "Alt+Shift+F3" },
  ],
  run: [
    { label: "Start Debugging", shortcut: "F5" },
    { label: "Run Without Debugging", shortcut: "Ctrl+F5" },
    { label: "Stop Debugging", shortcut: "Shift+F5" },
    { label: "Restart Debugging", shortcut: "Ctrl+Shift+F5" },
    { label: "Open Configurations", shortcut: "" },
    { label: "Add Configuration...", shortcut: "" },
    { label: "Step Over", shortcut: "F10" },
    { label: "Step Into", shortcut: "F11" },
    { label: "Step Out", shortcut: "Shift+F11" },
    { label: "Continue", shortcut: "F5" },
    { label: "Toggle Breakpoint", shortcut: "F9" },
    {
      label: "New Breakpoint",
      items: [
        { label: "Conditional Breakpoint..." },
        { label: "Edit Breakpoint" },
        { label: "Inline Breakpoint", shortcut: "Shift+F9" },
        { label: "Function Breakpoint" },
        { label: "Logpoint..." },
        { label: "Triggered Breakpoint..." },
      ],
    },
    { label: "Enable All Breakpoints" },
    { label: "Disable All Breakpoints" },
    { label: "Remove All Breakpoints" },
    { label: "Install Additional Debuggers..." },
  ],
  terminal: [
    { label: "New Terminal", shortcut: "" },
    { label: "Split Terminal", shortcut: "Ctrl+Shift+5" },
    { label: "Run Task...", shortcut: "" },
    { label: "Run Build Task...", shortcut: "Ctrl+Shift+B" },
    { label: "Run Active File", shortcut: "" },
    { label: "Run Selected Text", shortcut: "" },
    { label: "Show Running Tasks...", disabled: true, shortcut: "" },
    { label: "Restart Running Task...", disabled: true, shortcut: "" },
    { label: "Terminate Task...", disabled: true, shortcut: "" },
    { label: "Configure Tasks...", shortcut: "" },
    { label: "Configure Default Build Task...", shortcut: "" },
  ],
  help: [
    { label: "Welcome", shortcut: "" },
    { label: "Show All Commands", shortcut: "Ctrl+Shift+P" },
    { label: "Documentation", shortcut: "" },
    { label: "Editor Playground", shortcut: "" },
    { label: "Show Release Notes", shortcut: "" },
    { label: "Keyboard Shortcuts Reference [Ctrl+K Ctrl+R]", shortcut: "" },
    { label: "Video Tutorials", shortcut: "" },
    { label: "Tips and Tricks", shortcut: "" },
    { label: "Join Us on Youtube", shortcut: "" },
    { label: "Search Feature Request", shortcut: "" },
    { label: "Report Issue", shortcut: "" },
    { label: "View License", shortcut: "" },
    { label: "Privacy Statement", shortcut: "" },
    { label: "Toggle Developer Tools", shortcut: "" },
    { label: "Open Process Explorer", shortcut: "" },
    { label: "Check for Updates...", shortcut: "" },
    { label: "About", shortcut: "" },
  ],
};

export const allMobileApps = [
  { label: "Notepad", iconImage: "/icons/notepad-2.png" },
  { label: "Camera", iconImage: "/icons/camera.png" },
  { label: "Documents", iconImage: "/folder.png" },
  { label: "Files", iconImage: "/file.png" },
  { label: "Calendar", iconImage: "/calendar-3.png" },
  {
    label: "Internet",
    iconImage: "/internet-explorer-blue-e-icon-pixelated.jpg",
  },
  {
    label: "Gallery",
    iconImage: "/windows-98-picture-frame-with-tree-icon-pixelated.jpg",
  },
  {
    label: "Play Store",
    iconImage: "/colorful-play-button-triangle-red-blue-yellow-icon.jpg",
  },
  { label: "OneDrive", iconImage: "/gray-cloud-icon-pixelated.jpg" },
  { label: "Maps", iconImage: "/globe-earth-icon-green-blue-pixelated.jpg" },
  { label: "Clock", iconImage: "/pixelated-clock-icon-windows-98-style.jpg" },
  { label: "Word", iconImage: "/document-icon-pixelated.jpg" },
  { label: "Notes", iconImage: "/notepad-icon-pixelated.jpg" },
  { label: "Pictures", iconImage: "/picture-icon-pixelated.jpg" },
  { label: "Photos", iconImage: "/image-icon-pixelated.jpg" },
  {
    label: "Preferences",
    iconImage: "/pixelated-settings-gear-icon-windows-98.jpg",
  },
  {
    label: "My Computer",
    iconImage: "/pixelated-computer-monitor-icon-windows-98.jpg",
  },
  {
    label: "Recycle Bin",
    iconImage: "/pixelated-recycle-bin-trash-icon-windows-98.jpg",
  },
  {
    label: "Games",
    iconImage: "/pixelated-game-controller-icon-windows-98.jpg",
  },
  {
    label: "Media Player",
    iconImage: "/pixelated-music-note-icon-windows-98.jpg",
  },
  {
    label: "Mail",
    iconImage: "/pixelated-envelope-mail-icon-windows-98.jpg",
  },
];
